/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "listdir.h"
#include <errno.h>

void
dir_list_prog_1(char *host, char* path)
{
	CLIENT *clnt;
	readdir_ret  *result_1;
    //Set possible size of path to MAXLEN as defined in the header, use strncpy to copy
    //and manually add a null terminator.
	nametype  readdir_1_arg = malloc(sizeof(char)*MAXLEN+1);
    strncpy(readdir_1_arg, path, MAXLEN);
    readdir_1_arg[MAXLEN] = '\0';
    
    
#ifndef	DEBUG
	clnt = clnt_create (host, DIR_LIST_PROG, DIR_LIST_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	result_1 = readdir_1(&readdir_1_arg, clnt);
	if (result_1 == (readdir_ret *) NULL) {
		clnt_perror (clnt, "call failed");
	}else{
      if(result_1->err!=0){
        //If err is not 0, an error occurred so set errno to err, print it, and exit.
        errno = result_1->err;
        perror("Error");
        exit(1);
      }else{
        //On success, traverse the linked list and print out each name with a newline after it.
        namelist nodeptr=result_1->readdir_ret_u.list;
        while(nodeptr!=NULL){
          printf("%s\n", nodeptr->name);
          nodeptr=nodeptr->next;
        }
      }
    }
    //Free client memory before closing everything.
    clnt_freeres(clnt, (xdrproc_t)xdr_readdir_ret, result_1);
#ifndef	DEBUG
    clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
    char *path;
	if (argc < 3) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
    path = argv[2];
	dir_list_prog_1 (host, path);
exit (0);
}
